insert into Pays(sNom, sAbreviation) values('Canada', 'CAN');
insert into Pays(sNom, sAbreviation) values('États-Unis', 'USA');
insert into Province (sNom,sAbreviation,paysId) values('Québec', 'QC', 1);
insert into Province (sNom,sAbreviation,paysId) values('Manitoba', 'MB', 1);
insert into Province (sNom,sAbreviation,paysId) values('Ontario', 'ON', 1);
insert into Province (sNom,sAbreviation,paysId) values('Terre-Neuve-et-Labrador', 'NL', 1);
insert into Province (sNom,sAbreviation,paysId) values('Sascatchewan', 'SK', 1);
insert into Province (sNom,sAbreviation,paysId) values('Île-du-Prince-Édouard', 'PE', 1);
insert into Province (sNom,sAbreviation,paysId) values('Nouvelle-Écosse', 'NS', 1);
insert into Province (sNom,sAbreviation,paysId) values('Colombie-Britannique', 'BC', 1);
insert into Province (sNom,sAbreviation,paysId) values('Alberta', 'AB', 1);
insert into Province (sNom,sAbreviation,paysId) values('Nouveau-Brunswick', 'NB', 1);
insert into Province (sNom,sAbreviation,paysId) values('Nunavut', 'NU', 1);
insert into Province (sNom,sAbreviation,paysId) values('Yukon', 'YT', 1);
insert into Province (sNom,sAbreviation,paysId) values('Territoires du Nord-Ouest', 'NT', 1);
insert into province (snom, sabreviation, paysid) values('Alabama', 'AK', 2);
insert into province (snom, sabreviation, paysid) values('Alaska', 'AL', 2);
insert into province (snom, sabreviation, paysid) values('Arizona', 'AZ', 2);
insert into province (snom, sabreviation, paysid) values('Arkansas', 'AR', 2);
insert into province (snom, sabreviation, paysid) values('California', 'CA', 2);
insert into province (snom, sabreviation, paysid) values('Colorado', 'CO', 2);
insert into province (snom, sabreviation, paysid) values('Connecticut', 'CT', 2);
insert into province (snom, sabreviation, paysid) values('Delaware', 'DE', 2);
insert into province (snom, sabreviation, paysid) values('Florida', 'FL', 2);
insert into province (snom, sabreviation, paysid) values('Georgia', 'GA', 2);
insert into province (snom, sabreviation, paysid) values('Hawaii', 'HI', 2);
insert into province (snom, sabreviation, paysid) values('Idaho', 'ID', 2);
insert into province (snom, sabreviation, paysid) values('Illinois', 'IL', 2);
insert into province (snom, sabreviation, paysid) values('Indiana', 'IN', 2);
insert into province (snom, sabreviation, paysid) values('Iowa', 'IA', 2);
insert into province (snom, sabreviation, paysid) values('Kansas', 'KS', 2);
insert into province (snom, sabreviation, paysid) values('Kentucky', 'KY', 2);
insert into province (snom, sabreviation, paysid) values('Louisiana', 'LA', 2);
insert into province (snom, sabreviation, paysid) values('Maine', 'ME', 2);
insert into province (snom, sabreviation, paysid) values('Maryland', 'MD', 2);
insert into province (snom, sabreviation, paysid) values('Massachusetts', 'MA', 2);
insert into province (snom, sabreviation, paysid) values('Michigan', 'MI', 2);
insert into province (snom, sabreviation, paysid) values('Minnesota', 'MN', 2);
insert into province (snom, sabreviation, paysid) values('Mississippi', 'MS', 2);
insert into province (snom, sabreviation, paysid) values('Missouri', 'MO', 2);
insert into province (snom, sabreviation, paysid) values('Montana', 'MT', 2);
insert into province (snom, sabreviation, paysid) values('Nebraska', 'NE', 2);
insert into province (snom, sabreviation, paysid) values('Nevada', 'NV', 2);
insert into province (snom, sabreviation, paysid) values('New Hampshire', 'NH', 2);
insert into province (snom, sabreviation, paysid) values('New Jersey', 'NJ', 2);
insert into province (snom, sabreviation, paysid) values('New Mexico', 'NM', 2);
insert into province (snom, sabreviation, paysid) values('New York', 'NY', 2);
insert into province (snom, sabreviation, paysid) values('North Carolina', 'NC', 2);
insert into province (snom, sabreviation, paysid) values('North Dakota', 'ND', 2);
insert into province (snom, sabreviation, paysid) values('Ohio', 'OH', 2);
insert into province (snom, sabreviation, paysid) values('Oklahoma', 'OK', 2);
insert into province (snom, sabreviation, paysid) values('Oregon', 'OR', 2);
insert into province (snom, sabreviation, paysid) values('Pennsylvania', 'PA', 2);
insert into province (snom, sabreviation, paysid) values('Rhode Island', 'RI', 2);
insert into province (snom, sabreviation, paysid) values('South Carolina', 'SC', 2);
insert into province (snom, sabreviation, paysid) values('South Dakota', 'SD', 2);
insert into province (snom, sabreviation, paysid) values('Tennessee', 'TN', 2);
insert into province (snom, sabreviation, paysid) values('Texas', 'TX', 2);
insert into province (snom, sabreviation, paysid) values('Utah', 'UT', 2);
insert into province (snom, sabreviation, paysid) values('Vermont', 'VT', 2);
insert into province (snom, sabreviation, paysid) values('Virginia', 'VA', 2);
insert into province (snom, sabreviation, paysid) values('Washington', 'WA', 2);
insert into province (snom, sabreviation, paysid) values('West Virginia', 'WV', 2);
insert into province (snom, sabreviation, paysid) values('Wisconsin', 'WI', 2);
insert into province (snom, sabreviation, paysid) values('Wyoming', 'WY', 2);
insert into statusutilisateur(sTitre) values('Connecté');
insert into statusutilisateur(sTitre) values('Déconnecté');
insert into statusutilisateur(sTitre) values('Inactif');
insert into Utilisateur(paysId,provinceId,statusUtilisateurId,sNom,sPrenom,sPassword,sCourriel) values(1,1,1,'Lamarre', 'Gabriel', 'gr007,,','1302743@bdeb.qc.ca');
insert into Utilisateur(paysId,provinceId,statusUtilisateurId,sNom,sPrenom,sPassword,sCourriel) values(1,1,1,'Mc Nicoll', 'Louis-Simon', 'gr007,,','1372883@bdeb.qc.ca');
insert into Utilisateur(paysId,provinceId,statusUtilisateurId,sNom,sPrenom,sPassword,sCourriel) values(1,1,1,'Bossé', 'Sophie', 'gr007,,','1322931@bdeb.qc.ca');
insert into Utilisateur(paysId,provinceId,statusUtilisateurId,sNom,sPrenom,sPassword,sCourriel) values(1,1,1,'Belhumeur', 'Hugo', 'gr007,,','1257837@bdeb.qc.ca');
insert into typeservice(sTitre) values('Plombier');
insert into typeservice(sTitre) values('Femmes de ménage');
insert into typeservice(sTitre) values('Électricien');
insert into typeservice(sTitre) values('Chauffeur');
insert into annonce(typeServiceId,utilisateurId,sDescription) values(1,1,'Réparation de tuyaux');
insert into annonce(typeServiceId,utilisateurId,sDescription) values(4,2,'Ne dépasse pas les limites de vitesses');
insert into annonce(typeServiceId,utilisateurId,sDescription) values(3,3,'Fils réparés bon!');
insert into annonce(typeServiceId,utilisateurId,sDescription) values(2,4,'Je néttoie de Belle Humeur');
insert into disponibilite(annonceId,dHeureDebut,dHeureFin) values(1, sysdate(),sysdate());
insert into disponibilite(annonceId,dHeureDebut,dHeureFin) values(2, sysdate(),sysdate());
insert into disponibilite(annonceId,dHeureDebut,dHeureFin) values(3, sysdate(),sysdate());
insert into disponibilite(annonceId,dHeureDebut,dHeureFin) values(4, sysdate(),sysdate());
insert into statuscontrat(sTitre) values('Demande d''info');
insert into statuscontrat(sTitre) values('Accepté');
insert into statuscontrat(sTitre) values('Pré-approuvé');
insert into statuscontrat(sTitre) values('Annulé');
insert into statuscontrat(sTitre) values('Impossible');
insert into statuscontrat(sTitre) values('Refusé');
insert into contrat(utilisateurId,annonceId,statusContratId) values(2,1,1);
insert into contrat(utilisateurId,annonceId,statusContratId) values(1,2,2);
insert into contrat(utilisateurId,annonceId,statusContratId) values(4,3,6);
insert into contrat(utilisateurId,annonceId,statusContratId) values(3,4,5);
insert into message(utilisateurId,contratId,sContenu,dEnvoie) values(2,1, 'Plombe moi', sysdate());
insert into message(utilisateurId,contratId,sContenu,dEnvoie) values(1,2, 'Chauffe moi', '2015-09-09');
insert into message(utilisateurId,contratId,sContenu,dEnvoie) values(4,3, 'Électrise moi', '2015-09-08');
insert into message(utilisateurId,contratId,sContenu,dEnvoie) values(3,4, 'Nettoie moi', '2015-09-07');